fin  = open("input.txt")
strings = fin.readlines()
mas = strings[0].split()
x1 = int(mas[0])
y1 = int(mas[1])
x2 = int(mas[2])
y2 = int(mas[3])
x3 = int(mas[4])
y3 = int(mas[5])
otv = 0.5 * (abs((x2 - x1) * (y3 - y1) - (x3 - x1) * (y2 - y1)))
print(otv)